# Generated by Django 3.0.3 on 2020-02-26 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avtoapp', '0002_post_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('vladeltsev', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('complectation', models.TextField()),
                ('box', models.TextField()),
                ('model', models.TextField()),
                ('modification', models.TextField()),
                ('pokolenie', models.TextField()),
                ('privod', models.TextField()),
                ('probeg', models.PositiveIntegerField()),
                ('rull', models.TextField()),
                ('sostoyanie', models.TextField()),
                ('type_engine', models.TextField()),
                ('type_kyzov', models.TextField()),
                ('color', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Marks',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='avto',
            name='cat_marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtoapp.Marks'),
        ),
        migrations.AddField(
            model_name='avto',
            name='cat_mesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtoapp.Mesto'),
        ),
    ]
